### ISSUE TITLE
trouble with custom_linky

### ISSUE THREAD

**Issue by thetux07** [BaQs/Home-AssistantConfig#1]
hello i have error with your custom linky,
can you help me ?

`Mon Dec 16 2019 17:02:05 GMT+0100 (heure normale d’Europe centrale)
Error while setting up platform linky_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 59, in setup_platform
    linky_data.update()
  File "/config/custom_components/linky_custom/sensor.py", line 212, in update
    self._fetch_data()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 199, in _fetch_data
    (today - relativedelta(months=12)))['data']:
  File "/usr/local/lib/python3.7/site-packages/pylinky/client.py", line 193, in get_data_per_period
    data = self._get_data(_MAP[_RESSOURCE][period_type], start, end)
  File "/usr/local/lib/python3.7/site-packages/pylinky/client.py", line 130, in _get_data
    raise PyLinkyEnedisException("Enedis.fr answered with an error: " + str(json_output))
pylinky.exceptions.PyLinkyEnedisException: Enedis.fr answered with an error: {'etat': {'valeur': 'erreur'}}`

thank you

**Comment by thetux07** [comment]
i have shearch for resolution, i have download pylinky and hae madec ommand python3 pylinky -m -u email@adress -p P@ssword and i have full information for my consuption but with custom_component i have error :( can you help me ?
thank you

**Comment by thetux07** [comment]
pardon je viens de voir que vous étiez de Lille du coup ca sera plus simple de dialoguer en Français :)

**Comment by BaQs** [comment]
Hi,
let's stick in English, other could read this :)

Did you manage to fix your issue ?

**Comment by thetux07** [comment]
Hello,
ok :) no, my problem it not resolved, i have always the same error
for test i recreate account on enedis but it don't working 
have you an idea ?

**Comment by thetux07** [comment]
hello,
i have resolve my probleme 
the problem was that I did not have 12 months of history, I change the value month = 12 to a lower value and it's ok,
